<?php

namespace AppBundle\Repository;

/**
 * UserProfileVisitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfileVisitRepository extends \Doctrine\ORM\EntityRepository
{
}
